version: '3.8'

services:
  threat-hunter:
    build: .
    environment:
      - MONGODB_URI=mongodb://threat-db:27017
      - ELK_VERSION=8.13.4
    ports:
      - "8080:8080"
    depends_on:
      - threat-db
      - elasticsearch

  threat-db:
    image: mongo:7.0
    volumes:
      - threat-data:/data/db
    ports:
      - "27017:27017"

  elasticsearch:
    image: elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.13.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  threat-data:
  es-data:
